name: create-draft-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (例: 1.0.0)'
        required: true

jobs:
  draft-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: process.env.TAG_NAME,
              draft: true,
              generate_release_notes: true
            })
        env:
          TAG_NAME: v${{ github.event.inputs.version }}

