name: generate-notes

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (例: 1.0.0)'
        required: true

jobs:
  generate-notes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/github-script@v6
        id: gen-notes
        with:
          script: |
            const result = await github.rest.repos.generateReleaseNotes({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: process.env.TAG_NAME
            })
            return result.data
        env:
          TAG_NAME: v${{ github.event.inputs.version }}
      - name: Empty commit
        run: |
          git config --global user.email "${GIT_AUTHOR_EMAIL}"
          git config --global user.name "${GIT_AUTHOR_NAME}"
          git switch -c ${BRANCH_NAME}
          git commit -m "chore: v${NEW_VERSION}" --allow-empty
          git push -u origin ${BRANCH_NAME}
        env:
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          NEW_VERSION: ${{ github.event.inputs.version }}
          BRANCH_NAME: version/v${{ github.event.inputs.version }}
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `chore: ${{ fromJson(steps.gen-notes.outputs.result).name }}`,
              head: process.env.BRANCH_NAME,
              base: "main",
              body: process.env.PR_BODY
            })
        env:
          BRANCH_NAME: version/v${{ github.event.inputs.version }}
          PR_BODY: ${{ fromJson(steps.gen-notes.outputs.result).body }}

